server:
  port: 9003

spring:
  application:
    name: ORDER-SERVICE

  # Cassandra
  # Driver / connection properties (Boot 3.x)
  cassandra:
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    keyspace-name: eshop_orders

  # Spring Data Cassandra properties
  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
